# Generated by Django 2.2.5 on 2019-09-22 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('nome', models.CharField(default='', max_length=30)),
                ('sobrenome', models.CharField(default='', max_length=30)),
                ('cpf', models.CharField(default='', max_length=14)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('data_de_nascimento', models.DateField(default=datetime.datetime(2019, 9, 22, 1, 49, 51, 925886))),
                ('endereço', models.CharField(default='', max_length=100)),
                ('telefone', models.CharField(default='', max_length=16)),
                ('sexo', models.IntegerField(choices=[(0, 'Masculino'), (1, 'Feminino')], default=0)),
                ('altura', models.FloatField(default=0.0)),
                ('peso_inicial', models.FloatField(default=0.0)),
                ('peso_atual', models.FloatField(default=0.0)),
                ('peso_objetivo', models.FloatField(default=0.0)),
                ('avaliações', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
