# Generated by Django 2.2.5 on 2019-09-22 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno_usuario',
            name='data_de_nascimento',
            field=models.DateField(default=datetime.datetime(2019, 9, 22, 1, 49, 57, 321266)),
        ),
    ]
